import { ROUTE } from './routes';
import { UserPermission } from './user-permission.enum';

export const navigationRoutes: ROUTE[] = [
  {
    icon: 'dashboard',
    activeImg: 'assets/svg/FacilityUserIcons/Dashboard.svg',
    inActiveImg: 'assets/svg/FacilityUserIcons/Dashboard (Hover).svg',
    route: 'dashboard',
    title: 'Dashboard',
    permissions: UserPermission.HAS_DASHBOARDS,
  },
  {
    icon: 'local_hospital',
    activeImg: 'assets/svg/ClockHealthUserIcons/Hospitals.svg',
    inActiveImg: 'assets/svg/ClockHealthUserIcons/Hospitals (Hover).svg',
    route: 'hospitals',
    title: 'Hospitals',
    permissions: UserPermission.HAS_HOSPITAL_PAGE,
  },
  {
    icon: 'ch_admin',
    activeImg: 'assets/svg/ClockHealthUserIcons/Admins.svg',
    inActiveImg: 'assets/svg/ClockHealthUserIcons/Admins (Hover).svg',
    route: 'ch-admins',
    title: 'CH Admins',
    permissions: UserPermission.HAS_HOSPITAL_PAGE,
  },
  {
    icon: 'add_business',
    activeImg: 'assets/svg/HospitalUserIcons/Facilities.svg',
    inActiveImg: 'assets/svg/HospitalUserIcons/Facilities (Hover).svg',
    route: 'facilities',
    title: 'Facilities',
    permissions: UserPermission.HAS_BRANCH_PAGE,
  },
  // {
  //   icon: 'house_siding',
  //   activeImg: 'assets/svg/AdminDashboardIconsActive/activeDashboard.svg',
  //   inActiveImg: 'assets/svg/AdminDashboardInActiveIcons/Dashboard.svg',
  //   route: 'caregivers',
  //   title: 'Caregivers',
  //   permissions: UserPermission.HAS_CAREGIVER_PAGE,
  // },
  {
    icon: 'add_circle_outline',
    activeImg: 'assets/svg/FacilityUserIcons/Users.svg',
    inActiveImg: 'assets/svg/FacilityUserIcons/Users (Hover).svg',
    route: 'users',
    title: 'Users',
    permissions: UserPermission.HAS_PROVIDER_PAGE,
  },
  {
    icon: 'how_to_reg',
    activeImg: 'assets/svg/FacilityUserIcons/Patients.svg',
    inActiveImg: 'assets/svg/FacilityUserIcons/Patients (Hover).svg',
    route: 'patients',
    title: 'Patients',
    permissions: UserPermission.HAS_ENROLLMENT_PAGE,
  },
  {
    icon: 'devices',
    activeImg: 'assets/svg/ClockHealthUserIcons/Device Info.svg',
    inActiveImg: 'assets/svg/ClockHealthUserIcons/Device Info (Hover).svg',
    route: 'devices',
    title: 'Device Info',
    permissions: UserPermission.HAS_DEVICE_PAGE,
  },
  {
    icon: 'history_edu',
    activeImg: 'assets/svg/ClockHealthUserIcons/Tickets.svg',
    inActiveImg: 'assets/svg/ClockHealthUserIcons/Tickets (Hover).svg',
    title: 'Tickets',
    route: 'tickets',
    permissions: UserPermission.HAS_DASHBOARDS,
  },
  // {
  //   icon: 'history_edu',
  //   activeImg: 'assets/svg/AdminDashboardIconsActive/activeTickets.svg',
  //   inActiveImg: 'assets/svg/AdminDashboardInActiveIcons/Tickets.svg',
  //   title: 'Configuration',
  //   route: 'configuration',
  //   permissions: UserPermission.HAS_DASHBOARDS,
  // },
  {
    icon: 'gesture',
    activeImg: 'assets/svg/FacilityUserIcons/Leader Board.svg',
    inActiveImg: 'assets/svg/FacilityUserIcons/Leader Board (Hover).svg',
    title: 'Leader Board',
    route: 'leader-board',
    permissions: UserPermission.HAS_CAREGIVER_PAGE,
  },

  // {
  //   icon: 'dns',
  //   route: 'claim',
  //   title: 'Claims',
  //   permissions: UserPermission.HAS_CLAIMS_PAGE,
  // },
  // {
  //   icon: 'list',
  //   route: 'patient/healthrecords',
  //   title: 'Patient Reports',
  //   permissions: UserPermission.HAS_PATIENT_REPORT_PAGE,
  // },
  // {
  //   icon: 'bug_report',
  //   route: 'request',
  //   title: 'Request',
  //   permissions: UserPermission.HAS_TICKETS_PAGE,
  // },
  {
    icon: 'settings',
    activeImg: 'assets/svg/ClockHealthUserIcons/Configuration.svg',
    inActiveImg: 'assets/svg/ClockHealthUserIcons/Configurations (Hover).svg',
    route: 'configuration',
    title: 'Configuration',
    permissions: UserPermission.HAS_SETTINGS_MODULE,
    // subMenu: [
    //   {
    //     icon: 'line_weight',
    //     activeImg:'assets/svg/AdminDashboardIconsActive/activeDashboard.svg',
    //     inActiveImg:'assets/svg/AdminDashboardInActiveIcons/Dashboard.svg',
    //     title: 'ICD Codes',
    //     route: 'settings/ICD',
    //   },
    //   // {
    //   //   icon: 'person',
    //   //   activeImg:'assets/svg/AdminDashboardIconsActive/activeDashboard.svg',
    //   //   inActiveImg:'assets/svg/AdminDashboardInActiveIcons/Dashboard.svg',
    //   //   title: 'Vendor List',
    //   //   route: 'settings/vendor-list',
    //   // },
    //   // {
    //   //   icon: 'perm_device_information',
    //   //   activeImg:'assets/svg/AdminDashboardIconsActive/activeDashboard.svg',
    //   //   inActiveImg:'assets/svg/AdminDashboardInActiveIcons/Dashboard.svg',
    //   //   title: 'Device Types',
    //   //   route: 'settings/device-type',
    //   // },
    //   // {
    //   //   icon: 'settings_cell',
    //   //   activeImg:'assets/svg/AdminDashboardIconsActive/activeDashboard.svg',
    //   //   inActiveImg:'assets/svg/AdminDashboardInActiveIcons/Dashboard.svg',
    //   //   title: 'Device Models',
    //   //   route: 'settings/device-model',
    //   // },
    //   {
    //     icon: 'star_rate',
    //     activeImg:'assets/svg/AdminDashboardIconsActive/activeDashboard.svg',
    //     inActiveImg:'assets/svg/AdminDashboardInActiveIcons/Dashboard.svg',
    //     title: 'Specialities',
    //     route: 'settings/specialty',
    //   },
    // ],
  },
  {
    icon: 'book',
    activeImg: 'assets/svg/FacilityUserIcons/Content Marketing.svg',
    inActiveImg: 'assets/svg/FacilityUserIcons/Content Marketing (Hover).svg',
    route: 'content-marketing',
    title: 'Content Marketing',
    permissions: UserPermission.HAS_CAREGIVER_PAGE,
  },
  {
    icon: 'book',
    activeImg: 'assets/svg/FacilityUserIcons/Reports.svg',
    inActiveImg: 'assets/svg/FacilityUserIcons/Reports (Hover).svg',
    route: 'reports/log-history',
    title: 'Reports',
    permissions: UserPermission.HAS_REPORTS,
    // subMenu: [
    //   {
    //     icon: 'history_edu',
    //     activeImg:'assets/svg/AdminDashboardIconsActive/activeDashboard.svg',
    //     inActiveImg:'assets/svg/AdminDashboardInActiveIcons/Dashboard.svg',
    //     title: 'Log History',
    //     route:'reports' ,
    //   },
    // ],
  },
];
